language: go

go:
  - 1.16.x


install:
  - go install github.com/securego/gosec/v2/cmd/gosec@latest
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin


script:
  - ./.travis.gofmt.sh
  - golangci-lint run ./...
  - go test -v ./...
  - gosec -tests ./...