language: go

go:
  - 1.16.x

before_install:
  - chmod +x .travis.gofmt.sh

install:
  - go install github.com/securego/gosec/v2/cmd/gosec@latest
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - ./.travis.gofmt.sh
  - golangci-lint run ./...
  - go test -v ./...
  - gosec -tests ./...
  - go build .
  - rm -f 'travis-ci-go-practice.zip' | zip -r 'travis-ci-go-practice.zip' *.go

deploy:
  # Use Github pages deploy process
  provider: pages
  # Keep builded pages
  skip-cleanup: true
  # Directory where your generated files are located
  file: travis-ci-go-practice.zip
  # Github security/auth token
  github-token: $GITHUB_TOKEN
  # Incremental commit to keep old build/files from previous deployments
  keep-history: true
  # Git branch on which it should deploy (master, gh-pages, foo...)
  target_branch: main
  on:
    # Which branch on commit/push will trigger deployment
    branch: main