language: go

go:
  - 1.16.x

before_install:
  - chmod +x .travis.gofmt.sh

install:
  - go install github.com/securego/gosec/v2/cmd/gosec@latest
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - ./.travis.gofmt.sh
  - golangci-lint run ./...
  - go test -v ./...
  - gosec -tests ./...
  - go build .
  - rm -f 'travis-ci-go-practice.zip' | zip -r 'travis-ci-go-practice.zip' *.go

before_deploy:
  - git config --local user.name "santiago-diaz-repo"
  - git config --local user.email "santiago.diaz5689@gmail.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG

deploy:
  provider: releases
  tag_name: $TRAVIS_TAG
  target_commitish: $TRAVIS_COMMIT
  name: $TRAVIS_TAG
  skip-cleanup: true
  file: travis-ci-go-practice.zip
  github-token: $GITHUB_TOKEN
  keep-history: true
  target_branch: main
  on:
    branch: main