language: go

go:
  - 1.16.x

before_install:
  - chmod +x .travis.gofmt.sh

install:
  - go install github.com/securego/gosec/v2/cmd/gosec@latest
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.42.1
  - go get -v -t ./...
  - export PATH=$PATH:$HOME/gopath/bin

script:
  - ./.travis.gofmt.sh
  - golangci-lint run ./...
  - go test -v ./...
  - gosec -tests ./...
  - go build .
  - rm -f 'travis-ci-go-practice.zip' | zip -r 'travis-ci-go-practice.zip' *.go


deploy:
  - provider: releases
    api_key:
      secure: "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"
    file: travis-ci-go-practice.zip
    skip_cleanup: true
    on:
      repo: santiago-diaz-repo/travis-ci-go-practice
      tags: false
      branches:
        only:
          - main